### ISSUE TITLE
Use PcgRandom instead of System.Random

### ISSUE THREAD

**Issue by bgrainger** [Haacked/Scientist.net#12]
[Line 13 of Scientist.cs](https://github.com/Haacked/Scientist.net/blob/dc8bbf5c1c7efad694335fe3bc6f00d0d5b8c925/src/Scientist/Scientist.cs#L13) says:

```
// TODO: Evaluate the distribution of Random and whether it's good enough.
```

PcgRandom ([NuGet](https://www.nuget.org/packages/PcgRandom), [GitHub](https://github.com/bgrainger/PcgRandom)) is a .NET port of the [PCG](http://www.pcg-random.org/) RNG algorithm. It's a drop-in replacement for `System.Random` that provides a high-quality PRNG.

If you're interested, I can submit a PR; just let me know. (I'd also fix the thread-safety bug in `Experiment.cs`; a `static` Random instance could be accessed simultaneously by multiple threads, but [it's not thread-safe](https://msdn.microsoft.com/en-us/library/system.random.aspx#ThreadSafety), and doing so can corrupt its internal state.)

**Comment by darcythomas** [comment]
My 10 cents:
The random object should be inject-able. That way we can write deterministic tests etc.

**Comment by jtreuting** [comment]
It feels like there needs to be some usage of Random first before it a decision is made on if it's randomness is "good enough" or not.

**Comment by Haacked** [comment]
I'd like to minimize 3rd party dependencies as much as possible.

In this case, perhaps we should switch to the [`RNGCryptoServiceProvider`](https://msdn.microsoft.com/en-us/library/system.security.cryptography.rngcryptoserviceprovider(v=vs.110).aspx)

It's thread safe.

**Comment by Haacked** [comment]
Great point about `System.Random` not being thread safe. I forgot about that!

**Comment by MovGP0** [comment]
the `RNGCryptoServiceProvider` and `PCGRandom` is much slower than `System.Random` and I don't see the advantage over a cryptographical random number generator over an more-or-less predictable but very fast pseudorandom generator in this case. 

On the contrary: it might cause a lot of problems in high-performance environments!

**Comment by MovGP0** [comment]
you can make System.Random thread save. put it into a static `Lazy<T>` and you get a thread save instance.

**Comment by MovGP0** [comment]
@darcythomas: i agree with that one. some users might just want to use a Round Robin method and using the `Interlocked` class on an static `int` value todo so.

**Comment by Haacked** [comment]
> you can make System.Random thread save. put it into a static Lazy<T> and you get a thread save instance.

How does that make it thread safe? It's the methods of `Random` that are not thread safe because they rely on some sort of internal state.

Per the MSDN article:

> If your app calls Random methods from multiple threads, you must use a synchronization object to ensure that only one thread can access the random number generator at a time.

**Comment by darcythomas** [comment]
@haacked I suspect @movGP0 means wrapping up a System.Random instance into a (new) singleton (using Lazy<>), with a lock(){} block around calls to random.Next for thread safety

**Comment by Haacked** [comment]
For fun, I did some benchmarking.

```csharp
var stopwatch = new Stopwatch();
var random = new Random();
var rng = new RNGCryptoServiceProvider();
var lockObj = new object();

const int iterations = 1000000;

// Probably don't need to call these methods to ensure they're JITTED since these are framework methods and they're probably
// NGen'd but JUST IN CASE.
byte[] _ = new byte[1];
rng.GetBytes(_);
random.NextBytes(_);

stopwatch.Start();
for (int i = 0; i < iterations; i++)
{
    byte[] bytes = new byte[1];
    rng.GetBytes(bytes);
}
stopwatch.Stop();
Console.WriteLine(iterations + " iterations of RNG: " + stopwatch.ElapsedMilliseconds + "ms");
stopwatch.Reset();
stopwatch.Start();
for (int i = 0; i < iterations; i++)
{
    lock(lockObj)
    {
        byte[] bytes = new byte[1];
        random.NextBytes(bytes);
    }
}
stopwatch.Stop();
Console.WriteLine(iterations + " iterations of Random: " + stopwatch.ElapsedMilliseconds + "ms");
```

Results

> 1000000 iterations of RNG: 397ms
> 1000000 iterations of Random: 32ms

In other words, `RNGCryptoServiceProvider` takes around 397 nanoseconds per call while `System.Random` takes 32 nanoseconds per call.

So yeah, `Random` even with a lock is faster, but at these speeds, it's just noise compared to the overhead . However, we're talking about a micro-optimization here in the first place. I think this speed difference is noise compared to other overheads of calling Scientist. Probably shouldn't call scientist in a tight loop if your app is that perf sensitive.

What's interesting is if you up the number of byes generated by `NextBytes`, System.Random starts to get slower. For example, to generate 164 bytes, Random takes longer than RNG.

For our needs, I think System.Random with a lock should be fine. Probably no need to wrap it in a `Lazy<T>` if we use a static initializer.

**Comment by MovGP0** [comment]
the thread savety on `System.Random` is only when creating multiple instances of it at the same time, since then those instances will be initialized with the same seed value. 

you can savely call the `.Next()` method without the lock.

**Comment by MovGP0** [comment]
the `Lazy` is needed to initialize the `Random` on the first use in a thread save way. without it, `Random` will be seeded on application start, which means that it will get the same seed than other static instances of `Random` without the `Lazy`. so i do recommend using it.

**Comment by bgrainger** [comment]
> you can savely call the .Next() method without the lock.

This is incorrect. From [the docs](https://msdn.microsoft.com/en-us/library/system.random.aspx#ThreadSafety):

> If your app calls Random methods from multiple threads, you must use a synchronization object to ensure that only one thread can access the random number generator at a time. If you don't ensure that the Random object is accessed in a thread-safe way, calls to methods that return random numbers return 0.

You cannot safely call `Next` from multiple threads simultaneously (which could happen when using the same `static` Random object in different HTTP requests).

**Comment by bgrainger** [comment]
The original suggestion in this issue won't be implemented, since it would involve taking an unnecessary third-party dependency. #34 is fixing the thread-safety issues. This issue is now redundant.

**Comment by MovGP0** [comment]
oh i see. thanks for checking 😃
