### ISSUE TITLE
Integrate the library with some CI Services

### ISSUE THREAD

**Issue by MarcosMeli** [Haacked/Scientist.net#13]
Hi Phil

Do you want my contribution creating the files and enabling services for integration with: 

TeamCity, Travis and AppVeyor

Like we have in FileHelpers: https://github.com/MarcosMeli/Filehelpers

Thanks for open source so many great libs !!!

**Comment by Haacked** [comment]
I'm already using AppVeyor and it seems to be working fine. :smile: Or am I missing something?

**Comment by MarcosMeli** [comment]
Great

I saw in the other PRs the integration now !!

If you want to integrate coverage or other service I would love to help

Thanks

**Comment by Haacked** [comment]
@MarcosMeli do you know how to do this? https://github.com/Haacked/Scientist.net/issues/35
