### ISSUE TITLE
Support different return types for Control/Candidate methods

### ISSUE THREAD

**Issue by akamud** [Haacked/Scientist.net#16]
This implementation depends on decisions made for #15.

Basically the idea is that sometimes the candidate code returns a different, but relatable value. For example:

```C#
public int ControlMethod(int foo)
{
    return 1;
}

public bool CandidateMethod(int foo)
{
    return true;
}
```

The candidate method now returns a `bool`, and while `bool` and `int` are different, you could easily map `1 -> true` and `0 -> false`.

This could be implemented creating a new interface `Experiment<TControl, TCandidate>` that would allow the user to specify different types for each method. In this case, providing a `Compare` method could even be required for the interface.

What do you think?

**Comment by akamud** [comment]
I was planning on creating a new interface for these cases, keeping the simpler interface so the user doesn't have to put `Experiment<bool, bool>`, for simple cases (which might be the majority of the time).

I'll commit what I implemented so we can discuss this better.

**Comment by Haacked** [comment]
Is there a pressing need for this? I worry about adding unnecessary complexity.

**Comment by akamud** [comment]
I understand, I think you can close this for now, custom comparators already enables more scenarios.
