### ISSUE TITLE
Script NuGet package creation

### ISSUE THREAD

**Issue by davezych** [Haacked/Scientist.net#38]
Things to figure out:
- Use DNU Pack or Nuget.exe? (or does it matter?)
- Do we want to auto push to nuget, or just create the package?
 - If we auto push, what branches should push?

@Haacked your thoughts? Anything else I'm missing?

**Comment by Haacked** [comment]
> Use DNU Pack or Nuget.exe? (or does it matter?)

I have to admit, I'm not caught up yet on the difference here. I want the package to work for .NET and .NET Core.

> Do we want to auto push to nuget, or just create the package?

Just create the package. AppVeyor has a NuGet feature so we can auto publish to the AppVeyor hosted NuGet feed. We can test that one and then push from AppVeyor to NuGet.

One thing to add is a way of managing release notes. For example, we use FAKE in Octokit.net. For each release, we post the [release notes in this document](https://github.com/octokit/octokit.net/blob/master/ReleaseNotes.md) and the FAKE task uses the version number in the heading for the new release and the release notes to update the version of the library and NuGet package.

We could steal that whole process.

**Comment by davezych** [comment]
>I have to admit, I'm not caught up yet on the difference here. I want the package to work for .NET and .NET Core.

After looking at this more I *think* we have to use `dnu pack`. I don't believe the nuget cli supports project.json's yet, and I don't see a reason to maintain the project details in both a project.json and a nuspec.

>Just create the package. AppVeyor has a NuGet feature so we can auto publish to the AppVeyor hosted NuGet feed. We can test that one and then push from AppVeyor to NuGet.

:+1: 

>One thing to add is a way of managing release notes.

Sounds good. I'll review the setup in octokit and update the build process.

**Comment by Haacked** [comment]
:cool: as long as a package created with dnu pack is a standard nuget package (which on reflection I don't see why it wouldn't be) that sounds good to me!

**Comment by davezych** [comment]
@Haacked Is your plan to handle version numbers solely in the release notes? (it looks like that's how it's handled in octokit?) 

When nuget-packing a .net core lib, it pulls the version from the `project.json`, so I'm not sure we need to pull the version out of the release notes as long as we're consistent in updating the project.json version. (I'll still pull the notes out to add to the nuget package, of course). 

Another thing, with .NET Core builds right now, if you have a version of `x.x.x-*`, the * will be replaced with the `DNX_BUILD_VERSION` env var value. I think what I'll do is set `DNX_BUILD_VERSION` to the appveyor build number so we'll get a nice version on non-release builds. 

Sound good?

**Comment by davezych** [comment]
Also, on that note, the current version in the json file is `1.0.0-*`, which should probably be rolled back to `0.1.0-*` or whatever.

**Comment by Haacked** [comment]
> @Haacked Is your plan to handle version numbers solely in the release notes? (it looks like that's how it's handled in octokit?)

That was my original plan, until I read...

> When nuget-packing a .net core lib, it pulls the version from the project.json, so I'm not sure we need to pull the version out of the release notes as long as we're consistent in updating the project.json version. (I'll still pull the notes out to add to the nuget package, of course).

My goal is to have one place to update the version number. We could perhaps update project.json based off of what's in the release notes. But I don't want to make this too much work so I'm open to your suggestions here.

> Another thing, with .NET Core builds right now, if you have a version of x.x.x-*, the * will be replaced with the DNX_BUILD_VERSION env var value. I think what I'll do is set DNX_BUILD_VERSION to the appveyor build number so we'll get a nice version on non-release builds.
> 
> Sound good?

:thumbsup:

**Comment by davezych** [comment]
@Haacked this can be closed too, right?
