### ISSUE TITLE
Do something about the unwieldy ExperimentInstance constructor.

### ISSUE THREAD

**Issue by Haacked** [Haacked/Scientist.net#57]
The constructor for  [`ExperimentInstance`](https://github.com/Haacked/Scientist.net/blob/master/src/Scientist/Internals/ExperimentInstance.cs#L28) has a lot of parameters. Because we want this to effectively be an read only instance, we need to supply all the parameters via the constructor.

Our options are:

1. Create a new `ExperimentSettings` class that has settable properties. Add a constructor overload to `ExperimentInstance` that takes a settings instance and sets all the properties accordingly.
2. Create a new `ExperimentBuilder` class that lets you set properties and returns a new instance of `ExperimentInstance` with those properties set via some `Create` method.
3. Add multiple ctor overloads to `ExperimentInstance`
4. Something I hadn't considered...

/cc @davezych who noted this problem

**Comment by joncloud** [comment]
I created a quick implementation of 1.  I figured i'd keep it simple, but we can definitely cook up another implementation if it seems more suitable.
