### ISSUE TITLE
Support multiple candidates

### ISSUE THREAD

**Issue by Haacked** [Haacked/Scientist.net#6]
The original Ruby library supports multiple candidates to compare to a control. We should do this. In fact, we should refactor the code to be a bit more in line with [the Ruby library](https://github.com/github/scientist/). We should only deviate where it makes sense because we're using C#

**Comment by RichardDalton** [comment]
Will have to learn me a bit of Ruby :smiley:

**Comment by joncloud** [comment]
I have worked on an implementation of this using a branch from my pull request #14. It's currently pushed out to https://github.com/joncloud/Scientist.net/tree/multipleBehaviors.

**Comment by Haacked** [comment]
Even though the Ruby implementation does this, I want to wait till someone else asks for it. I don't have any experiments that needs more than one candidates so far.
