### ISSUE TITLE
Experiment without Try

### ISSUE THREAD

**Issue by arntj** [Haacked/Scientist.net#70]
The Ruby docs says following about not adding a `Try` block in an experiment:

> If you don't declare any `try` blocks, none of the Scientist machinery is invoked and the control value is always returned.

From what I can see in the source code the behavior is identical in the .NET version, but this behavior is not clearly stated anywhere. I propose adding a test to verify that 'nothing' happens if you don't include a `Try` block in an experiment.

**Comment by Haacked** [comment]
Ah, good idea. Feel free to send a PR with such a test.

**Comment by arntj** [comment]
#73 closes this issue.

**Comment by Haacked** [comment]
Closed by #73
