### ISSUE TITLE
Logo (for NuGet, documentation, etc.)

### ISSUE THREAD

**Issue by jason-roberts** [Haacked/Scientist.net#75]
Noticed that logo is mentioned in #51 - just had a quick play with something like the attached. If you think it's suitable I can submit a PR with image..

![scientistlogo](https://cloud.githubusercontent.com/assets/1472335/18237692/033f8426-7367-11e6-8f87-474cadbf1a26.png)

**Comment by davezych** [comment]
I definitely like the simplicity of it. @Haacked do you know if the official ruby lib has a logo we should adapt for the c# port?

**Comment by Haacked** [comment]
@davezych I'll look into it.

**Comment by Haacked** [comment]
@jason-roberts I like it! Would you state in your PR that you're assigning rights to the image to GitHub, Inc.?

**Comment by jason-roberts** [comment]
@Haacked done... also included the SVG version so the project can edit in the future if required

**Comment by Haacked** [comment]
Hey all, just to close the loop on this. I talked to our creative team and while we liked the microscope idea,  we realized it didn't capture what the scientist library is about. In part, it's not about zooming in on something, it's about comparing two things (control and experiment).

So we went with something a bit more evocative of that.

| 256 x 256  |   
|---|
| ![scientist_final-01](https://cloud.githubusercontent.com/assets/11401067/18854833/06971aa6-8403-11e6-87a2-2ea76b40ee06.png)  |   

| 128 x 128 |
|---| 
| ![scientist_final-02](https://cloud.githubusercontent.com/assets/11401067/18854834/06985bbe-8403-11e6-8858-5d4856e41854.png) |

| 64 x 64 |
|---| 
| ![scientist_final-03](https://cloud.githubusercontent.com/assets/11401067/18854835/06987a54-8403-11e6-881a-b64fe137ed42.png) |

Thanks @jason-roberts! We didn't end up using what you created, but I appreciate the work anyways. It helped inspire us to where we ended up.

**Comment by jason-roberts** [comment]
No worries @Haacked  - I like the new one :)
